# version: 2.1
# orbs:
#   aws-s3: circleci/aws-s3@4.0.0
# jobs:
#   build:
#     docker:
#       - image: circleci/python:2.7-node
#     environment:
#       AWS_REGION: us-east-1
#     steps:
#       - checkout
#       - run: npm install
#       - run: npm run build
#       - aws-s3/sync:
#           from: dist
#           to: 's3://demo-ci-cd-article/'
#           arguments: |
#             --acl public-read \
#             --cache-control "max-age=86400" \
#           overwrite: true
# workflows:
#   version: 2.1
#   build:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              npm run build
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'master' ]; then
              aws s3 sync dist s3://demo-ci-cd-article-123/ --delete --exact-timestamps;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
